
---
    linters:
        flake8:
        eslint:
            config: 'stylelint.config.js'
        csslint:
    
    files:
        ignore:
            - 'src/generated/*'
            - 'webroot/bower_components/*'